INSERT INTO
    Student (
        STD,
        email,
        firstName,
        lastName,
        "group",
        CORstatus
    )
VALUES
    (
        'STD20001',
        'hei.alice.johnson@gmail.com',
        'Alice',
        'Johnson',
        'G1',
        TRUE
    ),
    (
        'STD20002',
        'hei.bob.smith@gmail.com',
        'Bob',
        'Smith',
        'J1',
        FALSE
    ),
    (
        'STD20003',
        'hei.charlie.williams@gmail.com',
        'Charlie',
        'Williams',
        'J2',
        TRUE
    ),
    (
        'STD20004',
        'hei.diana.brown@gmail.com',
        'Diana',
        'Brown',
        'H1',
        FALSE
    ),
    (
        'STD20005',
        'hei.ethan.jones@gmail.com',
        'Ethan',
        'Jones',
        'H2',
        TRUE
    ),
    (
        'STD20006',
        'hei.fiona.garcia@gmail.com',
        'Fiona',
        'Garcia',
        'G1',
        FALSE
    ),
    (
        'STD20007',
        'hei.george.miller@gmail.com',
        'George',
        'Miller',
        'J1',
        TRUE
    ),
    (
        'STD20008',
        'hei.hannah.davis@gmail.com',
        'Hannah',
        'Davis',
        'J2',
        FALSE
    ),
    (
        'STD20009',
        'hei.isaac.rodriguez@gmail.com',
        'Isaac',
        'Rodriguez',
        'H1',
        TRUE
    ),
    (
        'STD20010',
        'hei.julia.martinez@gmail.com',
        'Julia',
        'Martinez',
        'H2',
        FALSE
    ),
    (
        'STD20011',
        'hei.kevin.hernandez@gmail.com',
        'Kevin',
        'Hernandez',
        'G1',
        TRUE
    ),
    (
        'STD20012',
        'hei.lily.lopez@gmail.com',
        'Lily',
        'Lopez',
        'J1',
        FALSE
    ),
    (
        'STD20013',
        'hei.michael.gonzalez@gmail.com',
        'Michael',
        'Gonzalez',
        'J2',
        TRUE
    ),
    (
        'STD20014',
        'hei.nina.wilson@gmail.com',
        'Nina',
        'Wilson',
        'H1',
        FALSE
    ),
    (
        'STD20015',
        'hei.oscar.anderson@gmail.com',
        'Oscar',
        'Anderson',
        'H2',
        TRUE
    ),
    (
        'STD20016',
        'hei.paula.thomas@gmail.com',
        'Paula',
        'Thomas',
        'G1',
        FALSE
    ),
    (
        'STD20017',
        'hei.quincy.taylor@gmail.com',
        'Quincy',
        'Taylor',
        'J1',
        TRUE
    ),
    (
        'STD20018',
        'hei.rachel.moore@gmail.com',
        'Rachel',
        'Moore',
        'J2',
        FALSE
    ),
    (
        'STD20019',
        'hei.sam.jackson@gmail.com',
        'Sam',
        'Jackson',
        'H1',
        TRUE
    ),
    (
        'STD20020',
        'hei.tina.martin@gmail.com',
        'Tina',
        'Martin',
        'H2',
        FALSE
    ),
    (
        'STD20021',
        'hei.victor.bennett@gmail.com',
        'Victor',
        'Bennett',
        'G1',
        TRUE
    ),
    (
        'STD20022',
        'hei.zoe.fisher@gmail.com',
        'Zoe',
        'Fisher',
        'J1',
        FALSE
    ),
    (
        'STD20023',
        'hei.liam.cooper@gmail.com',
        'Liam',
        'Cooper',
        'J2',
        TRUE
    ),
    (
        'STD20024',
        'hei.mia.ward@gmail.com',
        'Mia',
        'Ward',
        'H1',
        FALSE
    ),
    (
        'STD20025',
        'hei.noah.bailey@gmail.com',
        'Noah',
        'Bailey',
        'H2',
        TRUE
    ),
    (
        'STD20026',
        'hei.olivia.turner@gmail.com',
        'Olivia',
        'Turner',
        'G1',
        FALSE
    ),
    (
        'STD20027',
        'hei.elijah.parker@gmail.com',
        'Elijah',
        'Parker',
        'J1',
        TRUE
    ),
    (
        'STD20028',
        'hei.sophia.evans@gmail.com',
        'Sophia',
        'Evans',
        'J2',
        FALSE
    ),
    (
        'STD20029',
        'hei.james.scott@gmail.com',
        'James',
        'Scott',
        'H1',
        TRUE
    ),
    (
        'STD20030',
        'hei.emily.green@gmail.com',
        'Emily',
        'Green',
        'H2',
        FALSE
    ),
    (
        'STD20031',
        'hei.jacob.hall@gmail.com',
        'Jacob',
        'Hall',
        'G1',
        TRUE
    ),
    (
        'STD20032',
        'hei.evelyn.adams@gmail.com',
        'Evelyn',
        'Adams',
        'J1',
        FALSE
    ),
    (
        'STD20033',
        'hei.benjamin.mitchell@gmail.com',
        'Benjamin',
        'Mitchell',
        'J2',
        TRUE
    ),
    (
        'STD20034',
        'hei.charlotte.campbell@gmail.com',
        'Charlotte',
        'Campbell',
        'H1',
        FALSE
    ),
    (
        'STD20035',
        'hei.daniel.king@gmail.com',
        'Daniel',
        'King',
        'H2',
        TRUE
    ),
    (
        'STD20036',
        'hei.amelia.carter@gmail.com',
        'Amelia',
        'Carter',
        'G1',
        FALSE
    ),
    (
        'STD20037',
        'hei.alexander.rivera@gmail.com',
        'Alexander',
        'Rivera',
        'J1',
        TRUE
    ),
    (
        'STD20038',
        'hei.ava.ramirez@gmail.com',
        'Ava',
        'Ramirez',
        'J2',
        FALSE
    ),
    (
        'STD20039',
        'hei.david.morris@gmail.com',
        'David',
        'Morris',
        'H1',
        TRUE
    ),
    (
        'STD20040',
        'hei.isabella.robinson@gmail.com',
        'Isabella',
        'Robinson',
        'H2',
        FALSE
    ),
    (
        'STD20041',
        'hei.joshua.lee@gmail.com',
        'Joshua',
        'Lee',
        'G1',
        TRUE
    ),
    (
        'STD20042',
        'hei.abigail.walker@gmail.com',
        'Abigail',
        'Walker',
        'J1',
        FALSE
    ),
    (
        'STD20043',
        'hei.joseph.hill@gmail.com',
        'Joseph',
        'Hill',
        'J2',
        TRUE
    ),
    (
        'STD20044',
        'hei.harper.allen@gmail.com',
        'Harper',
        'Allen',
        'H1',
        FALSE
    ),
    (
        'STD20045',
        'hei.samuel.young@gmail.com',
        'Samuel',
        'Young',
        'H2',
        TRUE
    ),
    (
        'STD20046',
        'hei.grace.wright@gmail.com',
        'Grace',
        'Wright',
        'G1',
        FALSE
    ),
    (
        'STD20047',
        'hei.andrew.hernandez@gmail.com',
        'Andrew',
        'Hernandez',
        'J1',
        TRUE
    ),
    (
        'STD20048',
        'hei.scarlett.hernandez@gmail.com',
        'Scarlett',
        'Hernandez',
        'J2',
        FALSE
    ),
    (
        'STD20049',
        'hei.matthew.lopez@gmail.com',
        'Matthew',
        'Lopez',
        'H1',
        TRUE
    ),
    (
        'STD20050',
        'hei.ella.harris@gmail.com',
        'Ella',
        'Harris',
        'H2',
        FALSE
    ),
    (
        'STD20051',
        'hei.jonathan.martinez@gmail.com',
        'Jonathan',
        'Martinez',
        'G1',
        TRUE
    ),
    (
        'STD20052',
        'hei.victoria.clark@gmail.com',
        'Victoria',
        'Clark',
        'J1',
        FALSE
    ),
    (
        'STD20053',
        'hei.carter.lewis@gmail.com',
        'Carter',
        'Lewis',
        'J2',
        TRUE
    ),
    (
        'STD20054',
        'hei.hazel.rodriguez@gmail.com',
        'Hazel',
        'Rodriguez',
        'H1',
        FALSE
    ),
    (
        'STD20055',
        'hei.lucas.thompson@gmail.com',
        'Lucas',
        'Thompson',
        'H2',
        TRUE
    ),
    (
        'STD20056',
        'hei.eleanor.white@gmail.com',
        'Eleanor',
        'White',
        'G1',
        FALSE
    ),
    (
        'STD20057',
        'hei.logan.hall@gmail.com',
        'Logan',
        'Hall',
        'J1',
        TRUE
    ),
    (
        'STD20058',
        'hei.elizabeth.young@gmail.com',
        'Elizabeth',
        'Young',
        'J2',
        FALSE
    ),
    (
        'STD20059',
        'hei.jack.martin@gmail.com',
        'Jack',
        'Martin',
        'H1',
        TRUE
    ),
    (
        'STD20060',
        'hei.sophie.king@gmail.com',
        'Sophie',
        'King',
        'H2',
        FALSE
    );